#!/bin/sh -e
file="${file:-"${1:-"/var/log/openqa"}"}"
options="${options:-""}"
logwarn="${logwarn:-$(command -v logwarn)}"
$logwarn ${options} -m '\[.*:?(debug|info|warn|error)\]' -p ${file} \
    '\[.*:?(warn|error)\]' '!\[.*:?(debug|info)\]' \ $@ \
    `# Maintain the list of ignored log messages` \
    `# in ./logwarn_openqa_ignore and NOT here` \
    | ./logwarn_openqa_ignore
