#!/bin/bash

journalctl --cursor-file=/var/lib/logwarn/openqa-gru -u openqa-gru \
    | grep \
        -e 'ERROR:' \
        -e 'WARNING:' \
    | grep --invert-match --perl-regexp \
        -e 'LLM API.*timed out' \
    || true
