#!/bin/sh -e
file="${file:-"${1:-"/var/log/openqa"}"}"
options="${options:-""}"
logwarn="${logwarn:-$(which logwarn)}"
$logwarn ${options} -m '\[.*:?(debug|info|warn|error)\]' -p ${file} \
    `# ignore known warnings mentioned in https://progress.opensuse.org/issues/13952` \
    '!got a status update but has no worker' \
    '!got an artefact but has no worker' \
    `# ignore broken registered assets https://progress.opensuse.org/issues/13938` \
    '!error\] Registering asset iso/.*:' \
    '!warn\] asset name .* invalid or does not exist' \
    '!is not in any job group, DELETE from assets where' \
    '!Registering asset' \
    `# https://progress.opensuse.org/issues/14904` \
    '!Can.*t call method .*DISTRI.* on an undefined value' \
    `# https://progress.opensuse.org/issues/14906` \
    '!Can.*t locate object method .*start_range.* via package .*Mojolicious::Plugin::AssetPack::Asset.*' \
    `# https://progress.opensuse.org/issues/15202` \
    '!is not in any job group, will delete in.*' \
    `# https://progress.opensuse.org/issues/17600` \
    '!duplicate key value violates unique constraint "job_templates_product_id_machine_id_test_suite_id"' \
    `# https://progress.opensuse.org/issues/17652` \
    '!Not an OpenID message' \
    `# https://progress.opensuse.org/issues/17762` \
    '!.*AMQP.*Connect timeout.*' \
    `# https://progress.opensuse.org/issues/17708` \
    '!dead job [0-9]+ aborted and duplicated [0-9]+' \
    `# https://progress.opensuse.org/issues/18048` \
    '!warn\] AMQP connection closed' \
    `# https://progress.opensuse.org/issues/18076 ` \
    '!warn\] no products found, retrying version wildcard' \
    `# https://progress.opensuse.org/issues/18162 ` \
    '!warn\] START_AFTER_TEST=.* not found - check for typos and dependency cycles' \
    `# https://progress.opensuse.org/issues/19424 ` \
    '!Worker not found for given connection during connection close' \
    `# https://progress.opensuse.org/issues/19674 ` \
    '!warn\] AMQP connection error: SSL connect attempt failed with unknown error' \
    `# https://progress.opensuse.org/issues/19730` \
    '!warn\] can.t remove.*png' \
    `# https://progress.opensuse.org/issues/19732` \
    '!scheduler:warn\] .* wants to grab a new job - killing the old one.*' \
    `# https://progress.opensuse.org/issues/19756` \
    '!websockets:error\] Unknown property received from worker .*' \
    `# https://progress.opensuse.org/issues/19794` \
    '!websockets:warn\] dead job .* aborted as incomplete' \
    `# https://progress.opensuse.org/issues/20218` \
    '!error\] Failed to login: OpenID provider returned invalid data\. Please retry again' \
    `# https://progress.opensuse.org/issues/21836` \
    '!websockets:warn\] A message received from unknown worker connection' \
    `# https://progress.opensuse.org/issues/21018` \
    '!warn\] Stopping worker .* immediately' \
    `# https://progress.opensuse.org/issues/23536` \
    '!error\] org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.' \
    `# https://progress.opensuse.org/issues/19674 ` \
    '!warn\] AMQP connection error: No route to host' \
    `# https://progress.opensuse.org/issues/29289` \
    '!warn\].*\/needles\/.*: No such file or directory' \
    '!error] Could not parse needle:.*' \
    `# https://progress.opensuse.org/issues/29478` \
    '!error\] Global symbol.*api_description.*not_found\.html\.ep' \
    `# https://progress.opensuse.org/issues/29481` \
    '!:error\] .*DBI Exception.*ERROR:  invalid input syntax for integer.* at .*Controller/Test.pm' \
    `# https://progress.opensuse.org/issues/40007` \
    '!warn\].*A message received from unknown worker connection' \
    `# https://progress.opensuse.org/issues/53399` \
    '!warn\].*Unable to get filename from .* Ignoring OPENQA_HOST_URL' \
    `# https://progress.opensuse.org/issues/53405` \
    '!warn\].*has no child, check its machine placed or dependency setting typos' \
    '\[.*:?(warn|error)\]' '!\[.*:?(debug|info)\]' $@
