#!/bin/bash

cat /dev/stdin | rg --engine pcre2 --invert-match \
    `# The following lines contain regexes of log lines to ignore known issues` \
    `# ignore known warnings mentioned in https://progress.opensuse.org/issues/13952` \
    -e 'got a status update but has no worker' \
    -e 'got an artefact but has no worker' \
    `# ignore broken registered assets https://progress.opensuse.org/issues/13938` \
    -e 'error\] Registering asset iso/.*:' \
    -e 'warn\] asset name .* invalid or does not exist' \
    -e 'is not in any job group, DELETE from assets where' \
    -e 'Registering asset' \
    `# https://progress.opensuse.org/issues/14904` \
    -e 'Can.*t call method .*DISTRI.* on an undefined value' \
    `# https://progress.opensuse.org/issues/14906` \
    -e 'Can.*t locate object method .*start_range.* via package .*Mojolicious::Plugin::AssetPack::Asset.*' \
    `# https://progress.opensuse.org/issues/15202` \
    -e 'is not in any job group, will delete in.*' \
    `# https://progress.opensuse.org/issues/17600` \
    -e 'duplicate key value violates unique constraint "job_templates_product_id_machine_id_test_suite_id"' \
    `# https://progress.opensuse.org/issues/17652` \
    -e 'Not an OpenID message' \
    `# https://progress.opensuse.org/issues/17762` \
    -e '.*AMQP.*Connect timeout.*' \
    `# https://progress.opensuse.org/issues/17708` \
    -e 'dead job [0-9]+ aborted and duplicated [0-9]+' \
    `# https://progress.opensuse.org/issues/18048` \
    -e 'warn\] AMQP connection closed' \
    `# https://progress.opensuse.org/issues/18076 ` \
    -e 'warn\] no products found, retrying version wildcard' \
    `# https://progress.opensuse.org/issues/18162 ` \
    -e 'warn\] START_AFTER_TEST=.* not found - check for typos and dependency cycles' \
    `# https://progress.opensuse.org/issues/19424 ` \
    -e 'Worker not found for given connection during connection close' \
    `# https://progress.opensuse.org/issues/19674 ` \
    -e 'warn\] AMQP connection error: SSL connect attempt failed with unknown error' \
    `# https://progress.opensuse.org/issues/19730` \
    -e 'warn\] can.t remove.*png' \
    `# https://progress.opensuse.org/issues/19732` \
    -e 'scheduler:warn\] .* wants to grab a new job - killing the old one.*' \
    `# https://progress.opensuse.org/issues/20218` \
    -e 'error\] Failed to login: OpenID provider returned invalid data\. Please retry again' \
    `# https://progress.opensuse.org/issues/21836` \
    -e 'websockets:warn\] A message received from unknown worker connection' \
    `# https://progress.opensuse.org/issues/21018` \
    -e 'warn\] Stopping worker .* immediately' \
    `# https://progress.opensuse.org/issues/106613` \
    -e 'error\].* DBIx::Class::Row::update\(\): Can.t update OpenQA::Schema::Result::JobLocks=.* row not found' \
    `# https://progress.opensuse.org/issues/23536` \
    -e 'error\] org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.' \
    `# https://progress.opensuse.org/issues/19674 ` \
    -e 'warn\] AMQP connection error: No route to host' \
    `# https://progress.opensuse.org/issues/29289` \
    -e 'warn\].*\/needles\/.*: No such file or directory' \
    -e 'error] Could not parse needle:.*' \
    `# https://progress.opensuse.org/issues/29478` \
    -e 'error\] Global symbol.*api_description.*not_found\.html\.ep' \
    `# https://progress.opensuse.org/issues/29481` \
    -e ':error\] .*DBI Exception.*ERROR:  invalid input syntax for integer.* at .*Controller/Test.pm' \
    `# https://progress.opensuse.org/issues/40007` \
    -e 'warn\].*A message received from unknown worker connection' \
    `# https://progress.opensuse.org/issues/53399` \
    -e 'warn\].*Unable to get filename from .* Ignoring OPENQA_HOST_URL' \
    `# https://progress.opensuse.org/issues/53405` \
    -e 'warn\].*has no child, check its machine placed or dependency setting typos' \
    `# https://progress.opensuse.org/issues/53435` \
    -e 'error\].*DBIx.*number of parameters must be between.*OpenQA/WebAPI/Controller/API/V1/Job' \
    `# https://progress.opensuse.org/issues/53474` \
    -e 'error\].*File exists at.*Schema/Result/Jobs' \
    `# https://progress.opensuse.org/issues/105921` \
    -e '\[error\].* Cannot read symbolic link .*/.run_last\): No such file or directory' \
    `# https://progress.opensuse.org/issues/105915` \
    -e '\[error\].* Needle file .*.json not found within /.*\.' \
    `# https://progress.opensuse.org/issues/105900` \
    -e '\[warn\].* Unable to wakeup scheduler: Request timeout' \
    `# https://progress.opensuse.org/issues/105918` \
    -e '\[warn\].* fatal: Invalid revision range .*\.\.' \
    `# https://progress.opensuse.org/issues/105930` \
    -e '\[warn\] \[pid:[0-9]*\] $' \
    `# https://progress.opensuse.org/issues/106756` \
    -e '\[error\].*cmd returned [0-9]*$' \
    `# https://progress.opensuse.org/issues/125459` \
    -e '\[error\].*naive_verify_failed_return' \
    `# https://progress.opensuse.org/issues/138536` \
    -e '\[error\].*Worker [0-9]+ has no heartbeat.*' \
    `# https://progress.opensuse.org/issues/183302` \
    -e '\[error\].*FATAL:.*the database system is shutting down.*' \
    `# https://progress.opensuse.org/issues/193897` \
    -e '\[error\].*invalid input syntax for type bigint' \
    `# https://progress.opensuse.org/issues/208083` \
    -e '\[error\].*Global symbol "\$job_groups_and_parents" requires explicit package name.*navbar\.html\.ep' \
    || true
