#!/bin/sh -e
file="${file:-"${1:-"/var/log/openqa"}"}"
options="${options:-""}"
logwarn="${logwarn:-$(which logwarn)}"
$logwarn ${options} -m '\[.*:(debug|info|warn|error)\]' -p ${file} \
    `# ignore known warnings mentioned in https://progress.opensuse.org/issues/13952` \
    '!got a status update but has no worker' \
    '!got an artefact but has no worker' \
    `# ignore broken registered assets https://progress.opensuse.org/issues/13938` \
    '!error\] Registering asset iso/.*:' \
    '!warn\] asset name .* invalid or does not exist' \
    '!is not in any job group, DELETE from assets where' \
    '!Registering asset' \
    `# https://progress.opensuse.org/issues/14904` \
    '!Can.*t call method .*DISTRI.* on an undefined value' \
    `# https://progress.opensuse.org/issues/14906` \
    '!Can.*t locate object method .*start_range.* via package .*Mojolicious::Plugin::AssetPack::Asset.*' \
    `# https://progress.opensuse.org/issues/15202` \
    '!is not in any job group, will delete in.*' \
    '\[.*:(warn|error)\]' '!\[.*:(debug|info)\]' $@
