#!/bin/bash

cat /dev/stdin | rg --engine pcre2 --invert-match \
    `# The following lines contain regexes of log lines to ignore known issues` \
    `# https://progress.opensuse.org/issues/106613` \
    -e 'error\].* DBIx::Class::Row::update\(\): Can.t update OpenQA::Schema::Result::JobLocks=.* row not found' \
    `# https://progress.opensuse.org/issues/29289` \
    -e 'warn\].*\/needles\/.*: No such file or directory' \
    -e 'error] Could not parse needle:.*' \
    `# https://progress.opensuse.org/issues/29481` \
    -e ':error\] .*DBI Exception.*ERROR:  invalid input syntax for integer.* at .*Controller/Test.pm' \
    `# https://progress.opensuse.org/issues/40007` \
    -e 'warn\].*A message received from unknown worker connection' \
    `# https://progress.opensuse.org/issues/53405` \
    -e 'warn\].*has no child, check its machine placed or dependency setting typos' \
    `# https://progress.opensuse.org/issues/53435` \
    -e 'error\].*DBIx.*number of parameters must be between.*OpenQA/WebAPI/Controller/API/V1/Job' \
    `# https://progress.opensuse.org/issues/53474` \
    -e 'error\].*File exists at.*Schema/Result/Jobs' \
    `# https://progress.opensuse.org/issues/105921` \
    -e '\[error\].* Cannot read symbolic link .*/.run_last\): No such file or directory' \
    `# https://progress.opensuse.org/issues/105915` \
    -e '\[error\].* Needle file .*.json not found within /.*\.' \
    `# https://progress.opensuse.org/issues/105900` \
    -e '\[warn\].* Unable to wakeup scheduler: Request timeout' \
    `# https://progress.opensuse.org/issues/105918` \
    -e '\[warn\].* fatal: Invalid revision range .*\.\.' \
    `# https://progress.opensuse.org/issues/105930` \
    -e '\[warn\] \[pid:[0-9]*\] $' \
    `# https://progress.opensuse.org/issues/106756` \
    -e '\[error\].*cmd returned [0-9]*$' \
    `# https://progress.opensuse.org/issues/183302` \
    -e '\[error\].*FATAL:.*the database system is shutting down.*' \
    `# https://progress.opensuse.org/issues/193897` \
    -e '\[error\].*invalid input syntax for type bigint' \
    `# https://progress.opensuse.org/issues/208083` \
    -e '\[error\].*Global symbol "\$job_groups_and_parents" requires explicit package name.*navbar\.html\.ep' \
    || true
