#!/bin/bash

# This script does the same as logwarn_openqa
# but fetches the logs from the journal

journalctl --cursor-file=/var/lib/logwarn/openqa-webui -u openqa-webui \
    | rg --engine pcre2 -e '\[.*:?(warn|error)\]' \
    | rg --engine pcre2 -e '\[.*:?(debug|info)\]' -v \
    `# Maintain the list of ignored log messages` \
    `# in ./logwarn_openqa_ignore and NOT here` \
    | ./logwarn_openqa_ignore
