#!/bin/bash -e
set -o pipefail

HOST=$(hostname --long)
SUBJECT="OpenQA logwarn report for $1 on $HOST"
SENDER="${SENDER:-"openqa-monitor@$HOST"}"
REPORTTO="${REPORTTO:-"nsinger@suse.de"}"
COLUMN_LIMIT="${COLUMN_LIMIT:-1000}"
LINE_LIMIT="${LINE_LIMIT:-1000}"

# automatically update the script while preserving maybe added hotfixes

pushd "$(dirname "$0")" > /dev/null
# git pull --quiet --rebase origin master # This sometimes fails with "cannot rebase onto multiple branches".
git fetch --quiet --all --prune
git rebase --quiet origin/master

# script exits with 1 if new errors are found so don't exit here on exitcode != 0
# limit the length of each line to prevent overly long lines killing even
# email clients, e.g. database exceptions list every single table index.
# also truncate after too many lines
WARNINGS=$(./"$1" "$2" || true)
OUTPUT=$(echo "$WARNINGS" | cut -c -$COLUMN_LIMIT | head -n $LINE_LIMIT || true)
LINENUM=$(echo "$WARNINGS" | wc -l)

if [ ! -z "$OUTPUT" ]; then
    suffix="Logs reported by script call: \"./$1 $2\""$'\nFor silences modify this script and add an ignore regex at:\nhttps://github.com/os-autoinst/openqa-logwarn/'
    echo "Found $LINENUM lines via $1"$'\n'"$OUTPUT"$'\n\n-- \n'"$suffix" | mail -r "$SENDER" -s "$SUBJECT" "$REPORTTO"
fi
