#!/bin/bash -e

source t/common

if ! logwarn -v &>/dev/null; then
  echo "logwarn needs to be installed"
  exit 1
fi

in_log=$(cat t/data/openqa-webui.log)
out=$(env options="-f /dev/null" file=t/data/openqa-webui.log sh -ex ./logwarn_openqa) || true

source t/openqa_shared

done-testing
